server:
  port: 58080
strongbox:
  cassandra:
    port: 49142
  graph:
    gremlin:
      server:
        enabled: false # enabled gremlin server allows graph visualization using HTTP
        configurationResource: classpath:conf/gremlin-server/gremlin-server.yaml